homeassistant:
  name: StonesAnchor
  latitude: !secret secret_latitude
  longitude: !secret secret_longitude
  elevation: 0
  unit_system: imperial
  time_zone: America/Los_Angeles
  customize: !include customize.yaml
  packages: !include_dir_named packages
  
default_config:
 # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
 # http:
 #   base_url: !secret secret_base
#shell_command:
#  restart_pow: touch ~/.pow/restart.txt
hacs:
  token: !secret secret_hacs

frontend:
  javascript_version: latest
  themes: !include_dir_merge_named themes

lovelace:
 mode: yaml

discovery:
  ignore:
    - sonos
    - samsung_tv
  enable:

cloud: 
alexa:

weather:
  - platform: darksky
    api_key: !secret dark_key
    mode: daily


##  BINARY SENSORS
#####################
binary_sensor:
  - platform: ping
    host: !secret ping_host
    count: 2
# Binary Sensor TABLET MOTION        
  - platform: mqtt
    name: tablet_motion
    state_topic: any/value
##  TABLET LIGHT
light:
  - platform: template
    lights:
      tablet_screen:
        turn_on:
        turn_off:
#        set_level:
# TABLET CAMERA
camera:
  - name: tablet_camera
    platform: generic
    still_image_url: !secret tablet_url

notify:
  - platform: alexa_media
    friendly_name: notify_echo
  - platform: pushbullet
    name: notify.christian
    api_key: !secret pushbullet_api

# Text to speech
tts:
  - platform: google_translate

panel_iframe:
  ide:
    title: IDE
    icon: mdi:code-braces
    url: !secret panel_ide

device_tracker:
  - platform: nmap_tracker
    hosts:
     - 192.168.0.1/24
     - 10.0.0.2
     - 10.0.0.15
  - platform: ping
    hosts:
      hostone: 192.168.0.1
  - platform: bluetooth_tracker
   
recorder:
  purge_keep_days: 2

# alarm_control_panel: !include resources/bwalarm/bwalarm.yaml
## Split up configuration
# alarm_control_panel: !include alarm.yaml
# panel_custom: !include panel_custom.yaml
script: !include scripts.yaml
group: !include_dir_merge_named groups
automation: !include automations.yaml
#automation: !include_dir_named automations.yaml
# script: !include_dir_named scripts
