## Notify hunny bunny when I arrive home

input_boolean:
  notify_home:
    name: Notify when someone arrives home
    initial: off
    icon: mdi:car
    
automation:
  alias: Arriving home
  trigger:
    platform: state
    entity_id: binary_sensor.tablet_motion
    to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.notify_home
    state: 'on'
  action:
    service: notify.pushbullet
    data:
      title: ""
      message: "Honey, I'm home!"


#    - service: input_boolean.turn_on
#      data:
#        entity_id: input_boolean.notify_home