################################
#
##        SENSORS
#
#################################
sensor:
  - platform: yr

  - platform: darksky
    api_key: !secret dark_key
    monitored_conditions:
    - summary
    - temperature
    - wind_speed
    - cloud_cover
    - humidity
    - minutely_summary
    - uv_index
    - sunrise_time
    - sunset_time


#############################
#
##  SENSORS TEMPLATES 
#
#############################3
  - platform: template
    scan_interval: 30000
    sensors:
      floorplan_date:
        friendly_name: 'Tablet Date'
        entity_id: []
        value_template: >-
          {{now().strftime("%A")}}, {{now().strftime("%B")}} {{now().strftime("%d")}}

  - platform: template
    scan_interval: 60
    sensors:
      floorplan_time:
        friendly_name: 'Tablet Time'
        entity_id: []
        value_template: >-
          {{now().strftime("%-I")}}:{{now().strftime("%M")}} {{now().strftime("%p")}}
      clock_time:
        friendly_name: 'Clock Time'
        entity_id: []
        value_template: >-
          {{now().strftime("%-I")}}:{{now().strftime("%M")}}

## Clock Time and Day
  - platform: template
    scan_interval: 30000
    sensors:
      clock_am_pm:
        friendly_name: 'AM/PM'
        entity_id: []
        value_template: >-
          {{now().strftime("%p")}}
      clock_day:
        friendly_name: 'Day'
        entity_id: []
        value_template: >-
          {{now().strftime("%A")}}
      clock_date:
        friendly_name: 'Clock Date'
        entity_id: []
        value_template: >-
          {{now().strftime("%B")}} {{now().strftime("%d")}} {{now().year}}

#  - platform: time_date
#    display_options:
#      - 'time'
#      - 'date'
#      - 'date_time'
#      - 'time_date'
#      - 'time_utc'
#      - 'beat' 
#SENSOR WORLD CLOCK
#  - platform: worldclock
#    time_zone: Australia/Sydney
#    name: Syndey Time
#  
#  - platform: worldclock
#    time_zone: Europe/London
#    name: Tea Time

##    TIME OF DAY SENSOR
#  - platform: template
#    sensors:
#      time_of_day:
#        value_template: >
#          {% set current_hour = strptime(states('sensor.time'), "%H:%M").hour %}
#          {% if current_hour < 12 %}
#          
#            Good Morning, Christian
#          {% elif 12 <= current_hour < 18 %}
#          
#            Good Afternoon, Christian
#          {% elif 18 <= current_hour < 23 %}
#          
#            Good Evening, Christian
#          {% else %}
#          
#            Good Night, Christian
#          {% endif %}